### ISSUE TITLE
Syntax error: Missing comma

### ISSUE THREAD

**Issue by mrtoner** [MikeSofaer/stop_censorship#1]
```
"regex" : ".{5}", ...
```

**Comment by MikeSofaer** [comment]
hi mrtoner,

That's not a syntax error, regex is the last key in that dictionary.  I appreciate your looking at the code, though!

**Comment by mrtoner** [comment]
Not according to the code posted at http://mikesofaer.github.com/stop_censorship/ -- there's a 'persistent' property following.

**Comment by MikeSofaer** [comment]
Yup, there was.  I was looking at the Readme.  Thank you!
