### ISSUE TITLE
Main web page has garbage paragraphs on the bottom

### ISSUE THREAD

**Issue by danyork** [MikeSofaer/stop_censorship#2]
http://mikesofaer.github.com/stop_censorship/  has 4 paragraphs of garbage text on the bottom of the page.  I'm assuming that they were NOT intended to be there???

**Comment by MikeSofaer** [comment]
Hi Dan,

That text is sample text so that you can get a better sense of how a page of text looks censored.  We should at least make that clear.

Thanks for mentioning it!

**Comment by danyork** [comment]
Ahhhhh.... yeah, I had no clue what those paragraphs were about and thought perhaps the site had been hacked in some way (although I couldn't think of _how_ off the top of my head).

Yes, putting some explanatory text there would be good.  This issue can obviously be closed.

**Comment by MikeSofaer** [comment]
Replaced the sample text, hope you like it better :-)

**Comment by danyork** [comment]
Belatedly I'll just say thanks!  The new sample text is awesome! :-)
